name: Documentation Issue
description: Report issues or suggest improvements for documentation
title: "[Docs]: "
labels: ["documentation", "triage"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for helping improve our documentation!

  - type: dropdown
    id: doc-type
    attributes:
      label: Documentation Type
      options:
        - README
        - CLAUDE.md
        - Hooks documentation
        - Commands documentation
        - Setup guide
        - API documentation
        - Code comments
        - Other
    validations:
      required: true

  - type: input
    id: location
    attributes:
      label: Document Location
      description: Which file or section?
      placeholder: "e.g., docs/HOOKS.md, lines 42-50"
    validations:
      required: true

  - type: dropdown
    id: issue-type
    attributes:
      label: Issue Type
      options:
        - Missing documentation
        - Incorrect information
        - Unclear explanation
        - Typo or grammar
        - Outdated content
        - Missing example
        - Broken link
        - Other
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: Description
      description: What's wrong or what's missing?
      placeholder: The documentation says... but it should...
    validations:
      required: true

  - type: textarea
    id: suggestion
    attributes:
      label: Suggested Fix
      description: If you have a suggestion for how to improve it
      placeholder: I think it should say...

  - type: checkboxes
    id: contribution
    attributes:
      label: Contribution
      options:
        - label: I am willing to submit a PR to fix this
